### ISSUE TITLE
After a few Downloads it gets a 403

### ISSUE THREAD

**Issue by Sagestum** [whats-happening-rightnow/justfor.fans.ripper#3]
Hi there, the first few things are downloading, but after a very short time it stops on a 403. 

`Traceback (most recent call last):
  File "app.py", line 150, in <module>
    parse_and_get(html_text)
  File "app.py", line 122, in parse_and_get
    photo_save(thispost)
  File "app.py", line 55, in photo_save
    urllib.request.urlretrieve(img[1], img[0])
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by dilemmax** [comment]
Is this still working for you? I don't want to spend money on a subscription if I can't rip. Thank you

**Comment by edwardsdean** [comment]
i have a fork of the code that is working, [https://github.com/edwardsdean/justfor.fans.ripper](https://github.com/edwardsdean/justfor.fans.ripper )

**Comment by dilemmax** [comment]
@edwardsdean sorry, I couldn't lodge an issue on your version. It's not working for me

**Comment by edwardsdean** [comment]
@dilemmax what issue are you having? Can you post some logs?

**Comment by dilemmax** [comment]
@edwardsdean Here you go. It created folders for accounts that I'm not subscribed to.

C:\Users\dilemmax\Downloads\Compressed\justfor.fans.ripper-main>py app.py 1434 b3a2cda7caba6fa4ea8224c816864a57
https://justfor.fans/ajax/getPosts.php?UserID=1434&Type=All&StartAt=0&Source=Home&UserHash4=b3a2cda7caba6fa4ea8224c816864a57
dirrtydancer
May 7, 2022, 5:00 am
v: <<exists skip>>: dirrtydancer\video\2022-05-07_💥 BOOM💥 this is one of the best threesome I have d....mp4
t: dirrtydancer\video\2022-05-07_💥 BOOM💥 this is one of the best threesome I have d....txt
wILsljb
May 6, 2022, 10:15 pm
list index out of range
t: wILsljb\video\2022-05-06_Subscribe to read this user's entries..txt
DaddynGinger69
May 6, 2022, 7:51 pm
list index out of range
t: DaddynGinger69\video\2022-05-06_Ginger getting off on our new lovesense toy..txt
JohnThomasXXX1
May 6, 2022, 7:08 pm
list index out of range
t: JohnThomasXXX1\video\2022-05-06_So horny at work today Who's coming by to suck my....txt
dirrtydancer
May 6, 2022, 6:00 pm
p: dirrtydancer\photo\2022-05-06_A day at the beach 🏖😈☀️.jpg
/images/blur1.jpg
Traceback (most recent call last):
  File "C:\Users\dilemmax\Downloads\Compressed\justfor.fans.ripper-main\app.py", line 191, in <module>
    parse_and_get(html_text)
  File "C:\Users\dilemmax\Downloads\Compressed\justfor.fans.ripper-main\app.py", line 161, in parse_and_get
    photo_save(thispost)
  File "C:\Users\dilemmax\Downloads\Compressed\justfor.fans.ripper-main\app.py", line 66, in photo_save
    response = requests.get(img[1], stream=True)
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\dilemmax\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/images/blur1.jpg': No schema supplied. Perhaps you meant http:///images/blur1.jpg?

**Comment by edwardsdean** [comment]
@dilemmax just updated my fork with some additional logging, try running that one, if that is still causing issues might need your login to help debug the issue if thats someting you would be comfortable with, looks like cross posts are causing some issues.

**Comment by dilemmax** [comment]
@edwardsdean not a problem. I did pay for a subscription to see if it works. I'll give it a go now.

**Comment by dilemmax** [comment]
@edwardsdean I think I got it working now. I had to unfollow accounts that I'm not subscribed to for it to work. Although, I'm not sure if it's because you've made changes as well.

Is there any chance you can scrape the links to a text file so I can use a download manager??

**Comment by edwardsdean** [comment]
@dilemmax i did try using pySmartDL which is a python download manager but the downloads kept failing, i think the CDN service has some limits on downloading, though it wouldnt be too hard to change the code to support this but im not really interested in doing that.

**Comment by edwardsdean** [comment]
@dilemmax my fork should have fixed the following accounts issues fixed now

**Comment by stelladraco27** [comment]
Anyone still needing a fix? I changed how the request and file saving works in the code and it works for me now. Let me know, I can post the fix here.

**Comment by nstern2** [comment]
> 

Please do!

**Comment by stelladraco27** [comment]
I made a fork [here](https://github.com/stelladraco27/ripper).
Download it and use it the same way. 
I made some changes that:
- fix the downloading issues
- save each multi-photo post to a folder (not a massive dump of files)

His code is alright, but he has literally 0 comments, it was and is mega hard to figure out lmao, so i'd really need some support if you want a rewrite or smthn.

Only known "bug" that I really won't care to fix because I no longer have a subscription I need to rip is that multi-posts (ones that have multiple images and videos) get saved to separate folders (One for images, one for videos), this creates some clutter. I wont fix it because I no longer have a subscription to rip. If that's an issue you want me to deal with I'd fix it if I get some cash or some IDs and hashes (Basically let me rip your stuff for development purposes lol, or just share anyways because I like free corn, I won't judge what kind it is XD).

Anyways, hope the fix helps.

**Comment by nstern2** [comment]
Weirdly I ran yours on a different day and it grabbed everything fine, but today it is no longer getting the correct dates, effectively overwriting everything.  It's not a big deal, I just need to manually prune my stuff when I notice it gets completed.
