### ISSUE TITLE
KeyError: 'src'

### ISSUE THREAD

**Issue by rock1244** [whats-happening-rightnow/justfor.fans.ripper#8]
Not really sure whats wrong, i used this once before with no errors but now it just doesn't want to work. not familiar with how to use, nevermind read the command center. but this is what comes up:
Traceback (most recent call last):
File "C:\Users\profile\Downloads\justfor.fans.ripper-main\app.py", line 150, in <module>
    parse_and_get(html_text)
  File "C:\Users\profile\Downloads\justfor.fans.ripper-main\app.py", line 122, in parse_and_get
    photo_save(thispost)
  File "C:\Users\profile\Downloads\justfor.fans.ripper-main\app.py", line 32, in photo_save
    imgsrc = img.attrs['src']
KeyError: 'src'

**Comment by FurryFaux** [comment]
I'm getting the same thing, is there any fix for this?
